### ISSUE TITLE
The function `Get_Details` handle list of urls without needed

### ISSUE THREAD

**Issue by raulpy271** [amantiwari1/youtube-GUI#13]
In the last pull request ([Added 'Add' btn](https://github.com/raulpy271/youtube-GUI/pull/2)) we change the behavior to handle a single url by time, but we don't change the behavior of this [function](https://github.com/amantiwari1/youtube-GUI/blob/a1935f7f5768fbef063e5e7c41993ee4fcacd30d/src/components/Input.tsx#L144), which act as the text area has a list of url. 

To change it, I refactored this function in the branch [refactor](https://github.com/raulpy271/youtube-GUI/tree/refactor). After the merge of this pull request #12, we can merge this branch too.

**Comment by amantiwari1** [comment]
Why one url ?   Multiple Url is fine. why do we need `arr.every()` because of avoid two same url but I have amazing idea to make optimize to remove `arr.every()` by using array store variable named `UrlExist`  url.  for example

if url is exist in `UrlExist` then do not call function `window.eel.Get_Data_Details_Playlists()` 

else then `UrlExist` push url and call function `window.eel.Get_Data_Details_Playlists()` 

I am going to optimize it  and working on it

**Comment by amantiwari1** [comment]
got fixed it !!!
